# The following redirect is intended for use with most SPAs that handle routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/api/*"
  to = "https://jobs.github.com:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}